name: OpenTechSchool
markdown: redcarpet
pygments: true
encoding: UTF-8
permalink: none

exclude: ['bower_components', 'sass', 'config.rb', 'gumby.json',
          'Gemfile', 'Gemfile.lock', 'README.md', 'CNAME']

sections:
  - name: Hour of Code
    workshops:
      - title: Blockly Games
        offline: /tutorials/blockly-games/
        url: https://blockly-games.appspot.com/
        source: https://github.com/google/blockly-games
        downloads: /tutorials/blockly-games-repo/generated/
        code: false
        desc: "Blockly Games is a series of educational games that teach 
              programming. It is designed for children who have not had 
              prior experience with computer programming."
      - title: Lightbot
        offline: /downloads/HourOfCode/lightbot.com.zip
        url: http://lightbot.com/hocflash.html
        downloads: /downloads/HourOfCode
        apk: /downloads/HourOfCode/Lightbot.apk
        code: false
        desc: "Program Lightbot to light up all of the blue squares!"
      - title: Run Marco!
        offline: http://marco.allcancode.com/
        url: http://allcancode.com/
        apk: "/downloads/HourOfCode/Run Marco!.apk"
        downloads: /downloads/HourOfCode
        code: false
        desc: "In this unforgettable journey, Marco meets with friends, 
               discovers the world and finds out about his famous ancestor."
  - name: Python
    workshops:
      - title: Python for Beginners
        offline: /tutorials/OpenTechSchool/python-beginners/
        url: http://opentechschool.github.io/python-beginners/
        source: https://github.com/OpenTechSchool/python-beginners/
        downloads: /downloads/Python
        code: false
        desc: "A tutorial for complete newbies, to help them get their feet 
              wet in programming."
#      - title: Introducing web apps with Flask
#        url: http://opentechschool.github.io/python-flask/
#        source: https://github.com/OpenTechSchool/python-flask/
#        code: https://github.com/OpenTechSchool/python-flask-code
#        desc: "So you wanna get dynamic, huh? Crafting up responsive web apps 
#              isn't hard with the Flask library for Python."
#      - title: Data Processing with Python
#        url: http://opentechschool.github.io/python-data-intro/
#        source: https://github.com/OpenTechSchool/python-data-intro/
#        code: false
#        desc: "Designed to release you from the chains of Excel, learn how to 
#              manipulate and graph data with python, for great insight!"
#      - title: Django 101
#        url: http://django-marcador.keimlink.de/
#        source: https://bitbucket.org/keimlink/django-marcador/
#        code: false
#        desc: "Django is a full-featured framework for writing python web 
#              applications quickly. Learn how to utilize its power!"
  - name: Javascript
    workshops:
      - title: Javascript, Day 1
        offline: /tutorials/OpenTechSchool/js-beginners-4h-workshop-1/
        url: http://opentechschool.github.io/js-beginners-4h-workshop-1/
        source: https://github.com/OpenTechSchool/js-beginners-4h-workshop-1/
        downloads: /downloads/Javascript
        code: false
        desc: "Beginning your path to becoming a Javascript ninja."
      - title: Javascript, Day 2
        offline: /tutorials/OpenTechSchool/js-beginners-day2/
        url: http://opentechschool.github.io/js-beginners-day2/
        source: https://github.com/OpenTechSchool/js-beginners-day2/
        downloads: /downloads/Javascript
        code: false
        desc: "Continuing on your path to becoming a Javascript ninja."
  - name: Hardware
    workshops:
      - title: StartHardware.org
        offline: /tutorials/starthardware.org/
        url: http://starthardware.org
        downloads: /downloads/Arduino
        code: false
        desc: "Here you learn, how you can program Arduinos yourself. 
              From blinking LEDs to your own digital pet you can explore 
              the exciting world of programmable hardware."
#  - name: Web Development
#    workshops:
#      - title: Starting HTML & CSS
#        url: http://opentechschool.github.io/html-css-beginners/
#        source: https://github.com/OpenTechSchool/html-css-beginners/
#        code: false
#        desc: "A first foray into learning the languages of the web: 
#              HTML and CSS."
#      - title: CSSclasses
#        url: http://cssclasses.cssconf.eu/learning-materials/
#        source: https://github.com/OpenTechSchool/CSSclasses/
#        code: false
#        desc: "Learn CSS in a playful way and experiment in the browser."
#  - name: Data Hacking
#    workshops:
#      - title: Working with SQL databases
#        url: http://opentechschool.github.io/sql-tutorial/
#        source: https://github.com/OpenTechSchool/sql-tutorial
#        code: false
#        desc: "Beginners' tutorial on how to extract information from databases with SQL"
#  - name: Tools
#    workshops:
#      - title: Social coding with Git & Github
#        url: http://opentechschool.github.io/social-coding/
#        source: https://github.com/OpenTechSchool/social-coding/
#        code: https://github.com/OpenTechSchool/underground/
#        desc: "Learning to use git to make coding a communal experience!"
#      - title: Github from Scratch
#        url: http://opentechschool.github.io/github-from-scratch/
#        source: https://github.com/OpenTechSchool/github-from-scratch/
#        code: false
#        desc: "Learning about Github, Jekyll and basic HTML / CSS."

